import { notFound } from 'next/navigation';
import Link from 'next/link';
import { z } from 'zod';
import { formatInTimeZone } from 'date-fns-tz';
import { requireAdmin } from '@/lib/auth';
import { db } from '@/lib/db';
import { statusLabel } from '@/lib/admin';
import { priceLabel, durationLabel } from '@/lib/pricing';
import type { Booking } from '@/lib/types';
import { AdminActions } from '@/components/admin-actions';
export default async function Detail({params}:{params:Promise<{id:string}>}){await requireAdmin();const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();const {data,error}=await db().from('bookings').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!data)notFound();const b=data as Booking;return <><Link href="/admin/bookings" className="text-link">← All bookings</Link><div className="eyebrow" style={{marginTop:30}}>{b.reference}</div><h1 className="page-title">{b.client_name}</h1><span className={`badge ${b.status}`}>{statusLabel[b.status]}</span>{b.sync_state!=='synced'&&<p className="notice">Calendar or email confirmation is still processing. David has been alerted if an update failed.</p>}<h2 className="small-heading">Special requests</h2><div className="notice" style={{whiteSpace:'pre-wrap'}}>{b.client_notes||'No special requests.'}</div><dl className="review-list"><dt>When</dt><dd>{formatInTimeZone(b.start_at,b.snapshot.timezone,'EEEE, MMMM d, yyyy · h:mm a zzz')}</dd><dt>Service</dt><dd>{b.snapshot.style}</dd><dt>Extras</dt><dd>{b.snapshot.addons.join(', ')||'None'}</dd><dt>Time together</dt><dd>{durationLabel(b.duration_min)}</dd><dt>Phone</dt><dd><a href={`tel:${b.client_phone}`}>{b.client_phone} ↗</a> · <a href={`sms:${b.client_phone}`}>Text client</a></dd><dt>Email</dt><dd><a href={`mailto:${b.client_email}`}>{b.client_email} ↗</a></dd><dt>Instagram</dt><dd>{b.client_instagram?<a href={`https://instagram.com/${encodeURIComponent(b.client_instagram.replace(/^@/,''))}`} target="_blank" rel="noreferrer">{b.client_instagram} ↗</a>:'Not provided'}</dd><dt>Price</dt><dd>{b.snapshot.breakdown.map((l,i)=><div key={i}>{l.label}: {priceLabel(l)}</div>)}<strong>Total: {b.snapshot.estimate}</strong></dd><dt>Booked</dt><dd>{formatInTimeZone(b.created_at,b.snapshot.timezone,'MMM d, yyyy · h:mm a')}</dd></dl>{b.calendar_url&&<a className="text-link" href={b.calendar_url} target="_blank" rel="noreferrer">Open in Google Calendar ↗</a>}<AdminActions id={id} status={b.status} initialNote={b.admin_notes??''}/></>;}
