'use client';
import { isDemo, demoSlots, addDemoBooking } from '@/lib/demo';
import { useEffect, useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import Link from 'next/link';
import { ChevronLeft, ChevronRight, ArrowRight, Check, Instagram, Mail } from 'lucide-react';
import { addMonths, format, startOfMonth, getDaysInMonth } from 'date-fns';
import { formatInTimeZone } from 'date-fns-tz';
import { detailsSchema } from '@/lib/schemas';
import { quote, durationLabel, durationRange, priceLabel } from '@/lib/pricing';
import { contact, depositSummary, policies } from '@/lib/business';
import { makeICS } from '@/lib/ics';
import type { Booking, Catalog, Selection } from '@/lib/types';
import { ServicePicker, QuoteSummary } from './service-picker';
type Details=z.infer<typeof detailsSchema>;
type Receipt={id:string;reference:string;start_at:string;end_at:string;price_cents:number;duration_min:number;snapshot:{style:string;addons:string[];estimate:string;deposit:string;timezone:string};calendarSaved:boolean;emailSent:boolean};
const hairPrep=policies.find(p=>p.id==='hair-prep')!;
const policyLink=<Link href="/#before-you-book" target="_blank">booking policies</Link>;
export function BookingFlow({catalog,initial,ready}:{catalog:Catalog;initial:Selection;ready:boolean}){
 const [selection,setSelection]=useState<Selection>(initial);
 const [step,setStep]=useState(0),[month,setMonth]=useState(startOfMonth(new Date())),[day,setDay]=useState(''),[start,setStart]=useState(''),[slots,setSlots]=useState<Record<string,string[]>>({}),[loading,setLoading]=useState(false),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[key,setKey]=useState('');
 const form=useForm<Details>({resolver:zodResolver(detailsSchema),defaultValues:{name:'',phone:'',email:'',instagram:'',notes:'',website:''}});
 useEffect(()=>setKey(crypto.randomUUID()),[]);
 const q=useMemo(()=>{try{return quote(catalog,selection);}catch{return null;}},[catalog,selection]);
 const online=ready||isDemo;
 useEffect(()=>{if(step!==1||!online||!q)return;let active=true;const controller=new AbortController();setLoading(true);setError('');setSlots({});const total=getDaysInMonth(month),days=Array.from({length:total},(_,i)=>format(new Date(month.getFullYear(),month.getMonth(),i+1),'yyyy-MM-dd'));const today=format(new Date(),'yyyy-MM-dd');const last=format(new Date(Date.now()+60*86400000),'yyyy-MM-dd');const valid=days.filter(d=>d>=today&&d<=last);(async()=>{const result:Record<string,string[]>={};for(let i=0;i<valid.length;i+=5){await Promise.all(valid.slice(i,i+5).map(async d=>{if(isDemo){result[d]=demoSlots(d,q.duration);return;}const res=await fetch(`/api/availability?date=${d}&duration=${q.duration}`,{signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.error);result[d]=data.slots;}));}if(active)setSlots(result);})().catch(e=>{if(active)setError(e.message||'Could not check availability.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;controller.abort();};},[month,q,step,online]);
 function move(next:number){setStep(next);setError('');document.getElementById('booking-top')?.scrollIntoView({block:'start'});}
 async function submit(){if(!q||!start||!key||submitting)return;setSubmitting(true);setError('');try{if(isDemo){
 const details=form.getValues(),id=crypto.randomUUID(),end=new Date(new Date(start).getTime()+q.duration*60000).toISOString();
 const snapshot={style:q.service.name,addons:q.extras.map(e=>e.name),breakdown:q.breakdown,estimate:q.estimate,timezone:'America/Toronto',deposit:`${depositSummary} No payment is needed in this demo.`};
 const booking:Booking={id,reference:`DEMO-${id.slice(0,6).toUpperCase()}`,status:'pending_deposit',style_id:q.service.id,addon_ids:selection.extras,start_at:start,end_at:end,blocked_until:new Date(new Date(end).getTime()+30*60000).toISOString(),price_cents:q.total,duration_min:q.duration,client_name:details.name,client_phone:details.phone,client_email:details.email,client_instagram:details.instagram,client_notes:details.notes,admin_notes:'',google_event_id:null,calendar_url:null,snapshot,sync_state:'demo',created_at:new Date().toISOString()};
 addDemoBooking(booking);setReceipt({...booking,calendarSaved:true,emailSent:false});return;
 }const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...selection,start,details:form.getValues(),idempotencyKey:key})});const data=await response.json();if(response.status===409){setStart('');setStep(1);setSlots({});setError(data.error);setKey(crypto.randomUUID());return;}if(!response.ok)throw new Error(data.error);setReceipt(data);}catch(e){setError((e as Error).message||'Something went wrong. Please retry.');}finally{setSubmitting(false);}}
 const picker=<ServicePicker catalog={catalog} value={selection} onChange={s=>{setSelection(s);setStart('');setDay('');setKey(crypto.randomUUID());}}/>;
 if(receipt)return <section className="receipt"><div className="receipt-icon"><Check size={30}/></div><div className="eyebrow">{receipt.reference}</div><h1 className="page-title">{isDemo?'Demo appointment saved.':receipt.calendarSaved?'Appointment saved.':'Request received.'}</h1><p className="page-intro">{isDemo?'You’ve completed the booking demo. No real appointment was created. You can view this sample booking in the demo dashboard.':receipt.calendarSaved?'You’re on the calendar. Your appointment is confirmed once your deposit is received.':'Your request is saved. Calendar confirmation is still processing; please wait for confirmation before sending a deposit.'}</p><div className="notice"><h2 className="small-heading">{receipt.snapshot.style}</h2><p>{formatInTimeZone(receipt.start_at,receipt.snapshot.timezone,'EEEE, MMMM d · h:mm a zzz')}</p>{receipt.snapshot.addons.length>0&&<p>Extras: {receipt.snapshot.addons.join(', ')}</p>}<p>{receipt.snapshot.estimate} · {durationLabel(receipt.duration_min)}</p></div>{receipt.calendarSaved&&<div className="notice"><strong>Your deposit</strong><p>{receipt.snapshot.deposit}</p></div>}<h2 className="small-heading">Before your appointment</h2><p>{hairPrep.intro}</p><ul className="prose">{hairPrep.items!.map(item=><li key={item}>{item}</li>)}</ul><p className="muted">{hairPrep.outro}</p><p className="muted">{isDemo?'No email was sent. This appointment is stored only in this browser tab for the demo.':receipt.emailSent?'Your confirmation email has been sent.':'Your email is still processing. Keep your booking reference.'}</p>{receipt.calendarSaved&&<button className="button" onClick={()=>{const url=URL.createObjectURL(new Blob([makeICS(receipt)],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download=`${receipt.reference}.ics`;a.click();URL.revokeObjectURL(url);}}>{isDemo?'Download sample calendar file':'Add to calendar'}</button>}{isDemo&&<Link className="button button-outline full-width" href="/demo/admin">View demo dashboard ↗</Link>}</section>;
 if(!online)return <div id="booking-top" className="estimator-grid"><div>{picker}</div><div><QuoteSummary catalog={catalog} selection={selection}/><RequestPanel catalog={catalog} selection={selection}/></div></div>;
 return <div id="booking-top"><div className="booking-progress" aria-label={`Step ${step+1} of 4`}>{['Service','Date & time','Details','Review'].map((s,i)=><span className={step===i?'active':''} key={s} aria-current={step===i?'step':undefined}><b>{i+1}</b>{s}</span>)}</div><div className="estimator-grid"><div>
 {step===0&&picker}
 {step===1&&<section><h2 className="small-heading">Choose a date and time.</h2><p className="muted">All times in Vaughan, Ontario (America/Toronto).</p><div className="calendar-header"><button className="icon-button" aria-label="Previous month" disabled={month<=startOfMonth(new Date())} onClick={()=>setMonth(addMonths(month,-1))}><ChevronLeft size={18}/></button><strong>{format(month,'MMMM yyyy')}</strong><button className="icon-button" aria-label="Next month" disabled={month>=startOfMonth(new Date(Date.now()+60*86400000))} onClick={()=>setMonth(addMonths(month,1))}><ChevronRight size={18}/></button></div><div className="calendar-grid">{['Su','Mo','Tu','We','Th','Fr','Sa'].map(d=><span className="weekday" key={d}>{d}</span>)}{Array.from({length:month.getDay()},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:getDaysInMonth(month)},(_,i)=>{const date=format(new Date(month.getFullYear(),month.getMonth(),i+1),'yyyy-MM-dd');return <button key={date} type="button" aria-label={format(new Date(month.getFullYear(),month.getMonth(),i+1),'EEEE, MMMM d')} aria-pressed={day===date} disabled={!slots[date]?.length||loading} className={day===date?'selected':''} onClick={()=>{setDay(date);setStart('');}}>{i+1}</button>;})}</div><p className="fine-print" role="status">{loading?'Checking the calendar…':isDemo?'Sample appointment times for demonstration only.':'Highlighted dates have available times.'}</p>{day&&<fieldset><legend>Available times</legend><div className="chips">{slots[day]?.map(time=><button type="button" className={`chip ${start===time?'selected':''}`} aria-pressed={start===time} key={time} onClick={()=>{setStart(time);setKey(crypto.randomUUID());}}>{formatInTimeZone(time,'America/Toronto','h:mm a')}</button>)}</div></fieldset>}<p className="notice">None of these times work? <a className="text-link" href={contact.instagramDmUrl} target="_blank" rel="noreferrer">Message me on Instagram ↗</a></p></section>}
 {step===2&&<form id="details-form" onSubmit={form.handleSubmit(()=>move(3))} noValidate><h2 className="small-heading">Your contact details.</h2><div className="form-grid">{([['name','Full name'],['phone','Phone number'],['email','Email address'],['instagram','Instagram handle (optional)']] as const).map(([key,label])=><div key={key}><label className="field-label" htmlFor={key}>{label}</label><input id={key} {...form.register(key)} type={key==='email'?'email':key==='phone'?'tel':'text'} autoComplete={key==='name'?'name':key==='phone'?'tel':key==='email'?'email':'off'} aria-invalid={!!form.formState.errors[key]} aria-describedby={form.formState.errors[key]?`${key}-error`:undefined}/>{form.formState.errors[key]&&<p className="field-error" id={`${key}-error`}>{form.formState.errors[key]?.message}</p>}</div>)}<div className="span-two"><label className="field-label" htmlFor="notes">Anything you’d like me to know? (optional)</label><textarea id="notes" {...form.register('notes')} maxLength={300} placeholder="Special requests or anything I should know about your hair…"/><span className="fine-print">Up to 300 characters.</span></div><label className="honeypot" aria-hidden="true">Website<input {...form.register('website')} tabIndex={-1} autoComplete="off"/></label><label className="check-label span-two"><input type="checkbox" {...form.register('prep')}/><span>I have read and agree to the {policyLink}.</span></label>{form.formState.errors.prep&&<p className="field-error">{form.formState.errors.prep.message}</p>}</div></form>}
 {step===3&&<section><h2 className="small-heading">Review your appointment.</h2><dl className="review-list"><dt>Service</dt><dd>{q?.service.name}</dd><dt>Extras</dt><dd>{q?.extras.map(e=>e.name).join(', ')||'None'}</dd><dt>Your time</dt><dd>{start&&formatInTimeZone(start,'America/Toronto','EEEE, MMMM d · h:mm a zzz')}</dd><dt>Your details</dt><dd>{form.getValues('name')}<br/>{form.getValues('phone')}<br/>{form.getValues('email')}</dd><dt>Your notes</dt><dd>{form.getValues('notes')||'No special requests.'}</dd></dl><div className="notice">{isDemo?'This will save a sample appointment in this browser tab. No calendar event, email, or payment will be created.':'Your appointment is confirmed once your CA$20 deposit is received. Deposit details appear after your request is saved.'}</div></section>}
 {error&&<div role="alert" className="status-message">{error}</div>}<div className="booking-actions">{step>0?<button className="button button-outline" onClick={()=>move(step-1)} disabled={submitting}>Back</button>:<span/>}{step===2?<button className="button" type="submit" form="details-form">Review booking <ArrowRight size={17}/></button>:step===3?<button className="button" onClick={submit} disabled={submitting}>{submitting?'Saving your appointment…':'Confirm booking'}</button>:<button className="button" disabled={!q||(step===1&&!start)} onClick={()=>move(step+1)}> {step===0?'Choose your time':'Your details'} <ArrowRight size={17}/></button>}</div></div><QuoteSummary catalog={catalog} selection={selection}/></div></div>;
}

// Until online booking is switched on, clients send their chosen service to Sika directly.
function RequestPanel({catalog,selection}:{catalog:Catalog;selection:Selection}){
 const [copied,setCopied]=useState(false);
 let q;try{q=quote(catalog,selection);}catch{q=null;}
 const message=q?[`Hi Sika! I’d like to book:`,`${q.service.name} (${durationRange(q.service)})`,...q.breakdown.slice(1).map(l=>`+ ${l.label} (${priceLabel(l)})`),`Estimated total: ${q.estimate}`,'','Preferred date and time: ','Name: ','','I have read and agree to the booking policies.'].join('\n'):'';
 return <section className="request-panel" aria-labelledby="request-heading">
  <h2 id="request-heading" className="small-heading">Send your booking request.</h2>
  <p className="muted">Message me with your service and preferred date. I’ll confirm your time and send deposit details. By booking, you confirm that you have read and agree to the {policyLink}.</p>
  {q?<div className="request-actions">
   <a className="button full-width" href={contact.instagramDmUrl} target="_blank" rel="noreferrer" onClick={async()=>{try{await navigator.clipboard.writeText(message);setCopied(true);}catch{/* Clipboard can be blocked; the email option still carries the details. */}}}><Instagram size={18} aria-hidden="true"/> Book on Instagram</a>
   <a className="button button-outline full-width" href={`mailto:${contact.email}?subject=${encodeURIComponent(`Booking request: ${q.service.name}`)}&body=${encodeURIComponent(message)}`}><Mail size={18} aria-hidden="true"/> Book by email</a>
  </div>:<p className="notice">Choose a service above to send your request.</p>}
  {copied&&<p className="status-message" role="status">Your booking details are copied. Paste them into the Instagram chat.</p>}
 </section>;
}
